os: linux
dist: bionic
branches:
  except:
    - /^v\d+\.\d+\.\d+$/ # don't redundantly build tags
    - /^.*-version-bump-.*$/
before_install:
  # check what travis VMs we're using
  - nproc 2>/dev/null && python -c 'import multiprocessing;print multiprocessing.cpu_count()'
  - free && cat /proc/meminfo
  - echo "Travis Compiler ${TRAVIS_COMPILER}"
deploy:
  provider: releases
  api_key:
    secure: "oImiw4519op4e9DxYm47XlGnIpQJsLNRCEJT7PxVtyErTWInXGfQzwgpmAPud3o4xMBtYImhU8ozFYCl/p8Kppkj6maoI9Mh86Rm2FwA0R4QRjrUv0j2xayAoWygMOFCTHRDPeTQWEiyDP037SFvfI5vbjF9YWrq8WeN6OIyD4qApbTZ7eKyafEwKjt+iqRxpjN7Le1UszbdLdlQH0urpN/fskTavkXhNy+KVW95WaUxYT+9umQOGUkSfr2GrOjkl4P1d3trlKg/rCJwASYm7x5YljNXIEPTc9KeS41T5Zwki+kXRVKrdXasZs9PDHW5G16SL0FRPaDeU1ljENp4G+bb6mQNqaCFwsMVuNifqfmcrRvbacxqOuiD9cQ/wM0nfOgsULgtI+gP0JJRwjADeCTnLEGl3cqKuqbZUXPiU/wsWYDYX8R4/+EmNThEVLwKl459KEFVtMDUJRBu9OlAhvAmitYyboBpytDwWOd6UHZdtXqNsd4Rvi7LhwWtEizev0TVzYCxPTJu9/ffFgr4lWdoW3YThDI5FnbVRTIcrTH6TtGkSQMHQhmLOXDGUgxuWmw8k5x8IXVq5W74MAcV7a8oh2Nx6DGIxFr/IiaqkVIbB7DKVZ0ushtPcv6R6CDYl+kJRQPMb1pJ0rJY/23G4dCcNLf9fr9NfeNrd80lPLw="
  file: target/release/dynamodb-etl
  skip_cleanup: true
  draft: true
  on:
    # Omit tagged builds
    tags: false
    all_branches: true
    # Publish only on Rust jobs, on master and backport/* -- cannot be done with "branches" when "tags" is false
    # Maybe use TRAVIS_RUST_VERSION instead of TRAVIS_JOB_NAME?
    condition: $TRAVIS_JOB_NAME == "Rust" && ($TRAVIS_BRANCH == "master" || $TRAVIS_BRANCH == backport/*)
    repo: slamdata/customer-tools
stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
matrix:
  include:
    - name: "Scripts"
      language: shell
      script:
        - scripts/build.sh
    - name: "Rust"
      language: rust
      rust:
        - 1.37.0
      cache:
        - cargo
      before_script:
        - cd apps/dynamodb-etl
        - rustup component add clippy
      script:
        - cargo clippy --all-targets --all-features -- -D warnings
        - cargo check --all-targets --all-features
        - cargo build --verbose
        - cargo test --verbose
        - cargo build --release --verbose
