language: shell
script:
  - bash -c 'find . \( -name "*.sh" -or -name "*.ksh" -or -name "*.bash" \) -not -name osht.sh -prune -print0 | xargs -0 shellcheck'
  - find . -path '*/t/*.t' -perm +u+x -print0 | xargs -0 -t -I % bash %
